---
title: "Quarto presentations"
format: html
---

## Overview

This website hosts quarto presentations about microbiome analysis and data integration with mia and other related packages. Our presentations were prepared for past courses and conferences and cover a broad range of topics in the scope of biological data science. Currently, you can find the following subjects:

## Topics

- Intro
    - [Bioconductor](https://microbiome.github.io/outreach/bioconductor.html){target="_blank"}
    - [Reproducible reporting](https://microbiome.github.io/outreach/reproducible_reporting.html){target="_blank"}
    - [Data containers](https://microbiome.github.io/outreach/data_containers.html){target="_blank"}
    - [Import data](https://microbiome.github.io/outreach/import.html){target="_blank"}
- Preprocessing
    - [Agglomeration](https://microbiome.github.io/outreach/agglomeration.html){target="_blank"}
    - [Transformation](https://microbiome.github.io/outreach/transformation.html){target="_blank"}
- Diversity
    - [Alpha diversity](https://microbiome.github.io/outreach/alpha_diversity.html){target="_blank"}
    - [Beta diversity](https://microbiome.github.io/outreach/beta_diversity.html){target="_blank"}
        - [Ordination](https://microbiome.github.io/outreach/ordination.html){target="_blank"}
- Association
    - [Differential abundance analysis](https://microbiome.github.io/outreach/daa.html){target="_blank"}
- Multi-omics
    - [Multi-omics](https://microbiome.github.io/outreach/multi-omics.html){target="_blank"}
- Machine learning
    - [Machine learning](https://microbiome.github.io/outreach/machine_learning.html){target="_blank"}

### Packages

- [MGnifyR: An R package for accessing MGnify microbiome data](https://microbiome.github.io/outreach/mgnifyr.html){target="_blank"}
- [miaDash: Microbiome Analysis Dashboard](https://microbiome.github.io/outreach/miadash.html){target="_blank"}

### Data sets

- HintikkaXO
- Tengeler2020

### Conference and seminar presentations

- [Orchestrating microbiome multi-omics (BioC2023)](https://microbiome.github.io/outreach/bioc2023.html){target="_blank"}
- [Orchestrating Microbiome Analysis with Bioconductor (OH-BOOST, Microbiota Data Analysis and Statistics, webinar)](https://microbiome.github.io/outreach/oh-boost_webinar2024.html){target="_blank"}
- [Orchestrating Microbiome Analysis with Bioconductor (GBCC2025)](https://microbiome.github.io/outreach/gbcc2025.html){target="_blank"}
- [Orchestrating Microbiome Analysis with Bioconductor (ISMB/ECCB 2025)](https://microbiome.github.io/outreach/ismb_eccb2025.html){target="_blank"}

### Courses

- Intro
- [Brain, bacteria, and behaviour summer course](https://microbiome.github.io/outreach/brain_bacteria_behavior.html){target="_blank"}

## Contributions

You are welcome to add new presentations or improve the current ones. The guidelines for contributors are explained [here](https://github.com/microbiome/OMA#development-and-contributions). The presentations are deployed from the [quarto sub-directory](https://github.com/microbiome/outreach/blob/main/quarto/), so you need to make the respective changes there and run `cd quarto/; quarto render`.

The following is a quick workflow for contributions:

1.  fork the repository

2.  add your qmd file(s) to the [quarto sub-directory](https://github.com/microbiome/outreach/blob/main/quarto/)

3.  update the [\_quarto.yml file](https://github.com/microbiome/outreach/blob/main/quarto/_quarto.yml) and the list of presentations in the [website](https://github.com/microbiome/outreach/blob/main/quarto/index.qmd) with the name of the qmd file(s) with your presentation(s)

4.  run `quarto render`, or in R `quarto::quarto_render(myfilename)` from your terminal from within the quarto sub-directory

5.  and make a pull request to the master branch

[This documentation](https://quarto.org/docs/publishing/github-pages.html#publish-command) provides more details about publishing quarto presentations with GitHub Pages.
