---
title: "distance-based Redundance Analysis (dbRDA)"
format: html
editor: visual
---

## Overview

```{r}
#| label: setup
#| include: false
library(mia)
library(vegan)
library(scater)
library(ggplot2)
library(stringr)
library(ggord)

knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

To get started, we import Tengeler2020 from the mia package and store it into a variable.

```{r}
#| label: import-tengeler

# load dataset and store it into tse
data("Tengeler2020", package = "mia")
tse <- Tengeler2020
```

First off, we transform the counts assay to relative abundances and store the new assay back in the TreeSE.

```{r}
#| label: transform-relabundance
tse <- transformAssay(tse, method = "relabundance")
```

## Ordination

### RDA with Bray-Curtis index

```{r}
#| label: run-brayrda
tse <- runRDA(tse,
              formula = assay ~ patient_status + cohort,
              FUN = vegan::vegdist,
              method = "bray",
              assay.type = "relabundance")
```

```{r}
#| label: plot-brayrda
p <- plotReducedDim(tse, "RDA",
                    colour_by = "patient_status",
                    shape_by = "cohort")
```

```{r}
#| label: fig-brayrda
#| fig-cap: RDA plot with Bray-Curtis dissimilarity.
#| fig-width: 7
#| fig-asp: 0.7
#| echo: false
p
```

### RDA with Aitchison distance

```{r}
#| label: aitchison-workflow

# perform clr transformation
tse <- transformAssay(tse,
                       assay.type = "relabundance",
                       method = "clr",
                       pseudocount = 1)

# run RDA
tse <- runRDA(tse,
              formula = assay ~ patient_status + cohort,
              FUN = vegan::vegdist,
              method = "euclidean",
              assay.type = "clr",
              name = "Aitchison")

# plot RDA
p <- plotReducedDim(tse, "Aitchison",
                    colour_by = "patient_status",
                    shape_by = "cohort")
```

```{r}
#| label: fig-aitchirda
#| fig-cap: RDA plot with Aitchison distance (CLR assay + Euclidian distance).
#| fig-width: 7
#| fig-asp: 0.7
p
```

## Significance testing

### PERMANOVA analysis

```{r}
#| label: test-rda
#| echo: true
rda <- attr(reducedDim(tse, "RDA"), "rda")

set.seed(123)
terms_permanova <- anova.cca(rda,
                             permutations = 99)

set.seed(123)
margin_permanova <- anova.cca(rda,
                              by = "margin",
                              permutations = 99)
```

```{r}
#| label: tbl-permanova
#| tbl-cap: Results of PERMANOVA on patient_status and cohort groups.
#| echo: false
rda_info <- as.data.frame(rbind(terms_permanova["Model", ], margin_permanova))

rda_info[ , "Total variance"] <- rda_info["Model", "SumOfSqs"] + rda_info["Residual", "SumOfSqs"]

rda_info[ , "Explained variance"] <- rda_info[ , "SumOfSqs"] / rda_info[ , "Total variance"]

knitr::kable(rda_info)
```

### Test homogeneity assumption

```{r}
#| label: test-homogeneity
homo1 <- anova(betadisper(vegdist(t(assay(tse, "relabundance"))), tse$patient_status))
homo2 <- anova(betadisper(vegdist(t(assay(tse, "relabundance"))), tse$cohort))
```

```{r}
#| label: tbl-homogeneity
#| tbl-cap: Results of betadisper test on homogeneity.
#| echo: false
homogeneity <- as.data.frame(rbind(patient_status = homo1["Groups", ],
                                   cohort = homo2["Groups", ]))

knitr::kable(homogeneity)
```

## RDA plot with weights

```{r}
#| label: plot-rda
#| echo: false
coldata <- colData(tse)
variable_names <- c("patient_status", "cohort")

vec_lab_old <- rownames(rda$CCA$biplot)

vec_lab <- sapply(vec_lab_old, FUN = function(name){
    variable_name <- variable_names[ str_detect(name, variable_names) ]
    if( !any(name %in% variable_names) ){
        group_name <- unique( coldata[[variable_name]] )[ 
        which( paste0(variable_name, unique( coldata[[variable_name]] )) == name ) ]
        new_name <- paste0(variable_name, " \U2012 ", group_name)
    } else{
        new_name <- name
    }
    new_name <- expr(paste(!!new_name, " (", 
                           !!format(round( rda_info[variable_name, "Explained variance"]*100, 1), nsmall = 1), 
                           "%, ",italic("P"), " = ", 
                           !!gsub("0\\.","\\.", format(round( rda_info[variable_name, "Pr(>F)"], 3), 
                                                       nsmall = 3)), ")"))

    return(new_name)
})
names(vec_lab) <- vec_lab_old

xlab <- paste0("RDA1 (", format(round( rda$CCA$eig[[1]]/rda$CCA$tot.chi*100, 1), nsmall = 1 ), "%)")
ylab <- paste0("RDA2 (", format(round( rda$CCA$eig[[2]]/rda$CCA$tot.chi*100, 1), nsmall = 1 ), "%)")

plot <- ggord(rda, grp_in = coldata[["patient_status"]], vec_lab = vec_lab,
              alpha = 0.5,
              size = 4, addsize = -4,
              txt = 3.5, repel = TRUE, 
          ) + 
    guides(colour = guide_legend("patient_status"),
           fill = guide_legend("patient_status"),
           group = guide_legend("patient_status"),
           shape = guide_legend("patient_status"),
           x = guide_axis(xlab),
           y = guide_axis(ylab)) +
    theme( axis.title = element_text(size = 10) )
```

```{r}
#| label: fig-arrows
#| fig-cap: RDA plot of samples coloured by patient status. The arrows indicate the percentage of variance in beta diversity explained by the patient status or cohort and the respective p-value.
#| fig-width: 12
#| fig-height: 5
#| echo: false
plot
```
